#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := 133_ReferenceDesign_SampleCode

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/example/peripherals/spi_master/lcd_EPD_OK
EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/example/peripherals/usb/tusb_serial_device

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common
include $(IDF_PATH)/make/project.mk
